name: donde-ayudo-cl
region: nyc # O sfo (más cercano a Chile)

# Base de datos PostgreSQL
databases:
  - name: db
    engine: PG
    version: "16"
    production: false
    size: db-s-dev-database # $15/mes - 1GB RAM, 10GB disco

# Servicio usando Dockerfile (backend + frontend)
services:
  - name: app
    dockerfile_path: Dockerfile
    github:
      repo: P1ngu-Dev/Donde-Ayudo-CL
      branch: main
      deploy_on_push: true
    
    # Variables de entorno
    envs:
      - key: PORT
        value: "8080"
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET
        type: SECRET
        # Configurar en dashboard: Settings > Environment Variables
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: STATIC_DIR
        value: /app/public
    
    # Recursos
    instance_count: 1
    instance_size_slug: basic-xxs # $5/mes (512MB RAM - para ~200 usuarios)
    # Para emergencia con 500-1000 usuarios: professional-xs ($12/mes - 1GB RAM)
    # Para >1000 usuarios: professional-s ($24/mes - 2GB RAM, 2 vCPUs, autoscaling)
    
    # HTTP
    http_port: 8080
    
    # Health check
    health_check:
      http_path: /api
      initial_delay_seconds: 10
