name: donde-ayudo-cl
region: nyc # O sfo (más cercano a Chile)

# Servicio usando Dockerfile (backend + frontend)
services:
  - name: app
    dockerfile_path: Dockerfile
    github:
      repo: P1ngu-Dev/Donde-Ayudo-CL
      branch: main
      deploy_on_push: true
    
    # Variables de entorno
    envs:
      - key: PORT
        value: "8080"
      - key: ENVIRONMENT
        value: production
      - key: STATIC_DIR
        value: /app/public
      # JWT_SECRET y DATABASE_URL se configuran en: Settings > Environment Variables
    
    # Recursos
    instance_count: 1
    instance_size_slug: basic-xxs # $5/mes (512MB RAM - para ~200 usuarios)
    # Para emergencia con 500-1000 usuarios: professional-xs ($12/mes - 1GB RAM)
    # Para >1000 usuarios: professional-s ($24/mes - 2GB RAM, 2 vCPUs, autoscaling)
    
    # HTTP
    http_port: 8080
    
    # Health check
    health_check:
      http_path: /api
      initial_delay_seconds: 10
